// sale_by_customer actions...
export const ACCOUNT_TRANSACTION_REQUEST = "ACCOUNT_TRANSACTION_REQUEST";
export const ACCOUNT_TRANSACTION_SUCCESS = "ACCOUNT_TRANSACTION_SUCCESS";
export const ACCOUNT_TRANSACTION_FAILURE = "ACCOUNT_TRANSACTION_FAILURE";

export const GERNAL_LEDGER_REPORT_REQUEST = "GERNAL_LEDGER_REPORT_REQUEST";
export const GERNAL_LEDGER_REPORT_SUCCESS = "GERNAL_LEDGER_REPORT_SUCCESS";
export const GERNAL_LEDGER_REPORT_FAILURE = "GERNAL_LEDGER_REPORT_FAILURE";