// sale_by_customer actions...
export const ACCOUNT_TRANSACTION_REQUEST = "ACCOUNT_TRANSACTION_REQUEST";
export const ACCOUNT_TRANSACTION_SUCCESS = "ACCOUNT_TRANSACTION_SUCCESS";
export const ACCOUNT_TRANSACTION_FAILURE = "ACCOUNT_TRANSACTION_FAILURE";