export const DEBIT_NOTE_REPORT_REQUEST = "DEBIT_NOTE_REPORT_REQUEST";
export const DEBIT_NOTE_REPORT_SUCCESS = "DEBIT_NOTE_REPORT_SUCCESS";
export const DEBIT_NOTE_REPORT_FAILURE = "DEBIT_NOTE_REPORT_FAILURE";

export const CREDIT_NOTE_REPORT_REQUEST = "CREDIT_NOTE_REPORT_REQUEST";
export const CREDIT_NOTE_REPORT_SUCCESS = "CREDIT_NOTE_REPORT_SUCCESS";
export const CREDIT_NOTE_REPORT_FAILURE = "CREDIT_NOTE_REPORT_FAILURE";