export const VENDOR_SUMMARY_REPORT_REQUEST = "VENDOR_SUMMARY_REPORT_REQUEST";
export const VENDOR_SUMMARY_REPORT_SUCCESS = "VENDOR_SUMMARY_REPORT_SUCCESS";
export const VENDOR_SUMMARY_REPORT_FAILURE = "VENDOR_SUMMARY_REPORT_FAILURE";