export const PURCHASE_BY_VENDOR_REQUEST = "PURCHASE_BY_VENDOR_REQUEST";
export const PURCHASE_BY_VENDOR_SUCCESS = "PURCHASE_BY_VENDOR_SUCCESS";
export const PURCHASE_BY_VENDOR_FAILURE = "PURCHASE_BY_VENDOR_FAILURE";