export const CUSTOMER_SUMMARY_REPORT_REQUEST = "CUSTOMER_SUMMARY_REPORT_REQUEST";
export const CUSTOMER_SUMMARY_REPORT_SUCCESS = "CUSTOMER_SUMMARY_REPORT_SUCCESS";
export const CUSTOMER_SUMMARY_REPORT_FAILURE = "CUSTOMER_SUMMARY_REPORT_FAILURE";