// sale_by_customer actions...
export const SALE_BY_CUSTOMER_REQUEST = "SALE_BY_CUSTOMER_REQUEST";
export const SALE_BY_CUSTOMER_SUCCESS = "SALE_BY_CUSTOMER_SUCCESS";
export const SALE_BY_CUSTOMER_FAILURE = "SALE_BY_CUSTOMER_FAILURE";