// sale_by_customer actions...
export const SALE_BY_CUSTOMER_REQUEST = "SALE_BY_CUSTOMER_REQUEST";
export const SALE_BY_CUSTOMER_SUCCESS = "SALE_BY_CUSTOMER_SUCCESS";
export const SALE_BY_CUSTOMER_FAILURE = "SALE_BY_CUSTOMER_FAILURE";

export const SALE_BY_ITEM_REQUEST = "SALE_BY_ITEM_REQUEST";
export const SALE_BY_ITEM_SUCCESS = "SALE_BY_ITEM_SUCCESS";
export const SALE_BY_ITEM_FAILURE = "SALE_BY_ITEM_FAILURE";