export const CREATE_JOURNAL_REQUEST = "CREATE_JOURNAL_REQUEST";
export const CREATE_JOURNAL_SUCCESS = "CREATE_JOURNAL_SUCCESS";
export const CREATE_JOURNAL_ERROR = "CREATE_JOURNAL_ERROR";

export const GET_ACCOUNT_TYPE_REQUEST = "GET_ACCOUNT_TYPE_REQUEST";
export const GET_ACCOUNT_TYPE_SUCCESS = "GET_ACCOUNT_TYPE_SUCCESS";
export const GET_ACCOUNT_TYPE_ERROR = "GET_ACCOUNT_TYPE_ERROR";

export const CREATE_ACCOUNT_TYPE_REQUEST = "CREATE_ACCOUNT_TYPE_REQUEST";
export const CREATE_ACCOUNT_TYPE_SUCCESS = "CREATE_ACCOUNT_TYPE_SUCCESS";
export const CREATE_ACCOUNT_TYPE_ERROR = "CREATE_ACCOUNT_TYPE_ERROR";

export const ACCOUNT_STATUS_REQUEST = "ACCOUNT_STATUS_REQUEST";
export const ACCOUNT_STATUS_SUCCESS = "ACCOUNT_STATUS_SUCCESS";
export const ACCOUNT_STATUS_ERROR = "ACCOUNT_STATUS_ERROR";

export const ACCOUNT_DELETE_REQUEST = "ACCOUNT_DELETE_REQUEST";
export const ACCOUNT_DELETE_SUCCESS = "ACCOUNT_DELETE_SUCCESS";
export const ACCOUNT_DELETE_ERROR = "ACCOUNT_DELETE_ERROR";

export const ACCOUNT_DETAIL_REQUEST = "ACCOUNT_DETAIL_REQUEST";
export const ACCOUNT_DETAIL_SUCCESS = "ACCOUNT_DETAIL_SUCCESS";
export const ACCOUNT_DETAIL_ERROR = "ACCOUNT_DETAIL_ERROR";