

// Constants for updating ASSIST
export const ASSIST_UPDATE_REQUEST = 'ASSIST_UPDATE_REQUEST';
export const ASSIST_UPDATE_SUCCESS = 'ASSIST_UPDATE_SUCCESS';
export const ASSIST_UPDATE_ERROR = 'ASSIST_UPDATE_ERROR';


export const ASSIST_STATUS_REQUEST = "ASSIST_STATUS_REQUEST";
export const ASSIST_STATUS_SUCCESS = "ASSIST_STATUS_SUCCESS";
export const ASSIST_STATUS_ERROR = "ASSIST_STATUS_ERROR";

export const ASSIST_DELETE_REQUEST = "ASSIST_DELETE_REQUEST";
export const ASSIST_DELETE_SUCCESS = "ASSIST_DELETE_SUCCESS";
export const ASSIST_DELETE_ERROR = "ASSIST_DELETE_ERROR";

export const CREATE_ASSIST_REQUEST = "CREATE_ASSIST_REQUEST";
export const CREATE_ASSIST_SUCCESS = "CREATE_ASSIST_SUCCESS";
export const CREATE_ASSIST_ERROR = "CREATE_ASSIST_ERROR";


export const GET_ASSIST_REQUEST = "GET_ASSIST_REQUEST";
export const GET_ASSIST_SUCCESS = "GET_ASSIST_SUCCESS";
export const GET_ASSIST_ERROR = "GET_ASSIST_ERROR";

export const ASSIST_DETAIL_REQUEST = "ASSIST_DETAIL_REQUEST";
export const ASSIST_DETAIL_SUCCESS = "ASSIST_DETAIL_SUCCESS";
export const ASSIST_DETAIL_ERROR = "ASSIST_DETAIL_ERROR";


