export const BILL_LIST_REQUEST = "BILL_LIST_REQUEST";
export const BILL_LIST_SUCCESS = "BILL_LIST_SUCCESS";
export const BILL_LIST_ERROR = "BILL_LIST_ERROR";

export const BILL_DETAILS_REQUEST = "BILL_DETAILS_REQUEST";
export const BILL_DETAILS_SUCCESS = "BILL_DETAILS_SUCCESS";
export const BILL_DETAILS_ERROR = "BILL_DETAILS_ERROR";

export const BILL_DELETE_REQUEST = "BILL_DELETE_REQUEST";
export const BILL_DELETE_SUCCESS = "BILL_DELETE_SUCCESS";
export const BILL_DELETE_ERROR = "BILL_DELETE_ERROR";

export const PENDING_BILL_LIST_REQUEST = "PENDING_BILL_LIST_REQUEST";
export const PENDING_BILL_LIST_SUCCESS = "PENDING_BILL_LIST_SUCCESS";
export const PENDING_BILL_LIST_ERROR = "PENDING_BILL_LIST_ERROR";

export const BILL_STATUS_REQUEST = "BILL_STATUS_REQUEST";
export const BILL_STATUS_SUCCESS = "BILL_STATUS_SUCCESS";
export const BILL_STATUS_ERROR = "BILL_STATUS_ERROR";

export const BILL_SEND_REQUEST = "BILL_SEND_REQUEST";
export const BILL_SEND_SUCCESS = "BILL_SEND_SUCCESS";
export const BILL_SEND_ERROR = "BILL_SEND_ERROR";


export const HELP_SEND_REQUEST = "HELP_SEND_REQUEST";
export const HELP_SEND_SUCCESS = "HELP_SEND_SUCCESS";
export const HELP_SEND_ERROR = "HELP_SEND_ERROR";

