

// Constants for updating CARHIRE
export const CARHIRE_UPDATE_REQUEST = 'CARHIRE_UPDATE_REQUEST';
export const CARHIRE_UPDATE_SUCCESS = 'CARHIRE_UPDATE_SUCCESS';
export const CARHIRE_UPDATE_ERROR = 'CARHIRE_UPDATE_ERROR';


export const CARHIRE_STATUS_REQUEST = "CARHIRE_STATUS_REQUEST";
export const CARHIRE_STATUS_SUCCESS = "CARHIRE_STATUS_SUCCESS";
export const CARHIRE_STATUS_ERROR = "CARHIRE_STATUS_ERROR";

export const CARHIRE_DELETE_REQUEST = "CARHIRE_DELETE_REQUEST";
export const CARHIRE_DELETE_SUCCESS = "CARHIRE_DELETE_SUCCESS";
export const CARHIRE_DELETE_ERROR = "CARHIRE_DELETE_ERROR";

export const CREATE_CARHIRE_REQUEST = "CREATE_CARHIRE_REQUEST";
export const CREATE_CARHIRE_SUCCESS = "CREATE_CARHIRE_SUCCESS";
export const CREATE_CARHIRE_ERROR = "CREATE_CARHIRE_ERROR";


export const GET_CARHIRE_REQUEST = "GET_CARHIRE_REQUEST";
export const GET_CARHIRE_SUCCESS = "GET_CARHIRE_SUCCESS";
export const GET_CARHIRE_ERROR = "GET_CARHIRE_ERROR";

export const CARHIRE_DETAIL_REQUEST = "CARHIRE_DETAIL_REQUEST";
export const CARHIRE_DETAIL_SUCCESS = "CARHIRE_DETAIL_SUCCESS";
export const CARHIRE_DETAIL_ERROR = "CARHIRE_DETAIL_ERROR";


