export const CREATE_CUSTOMER_REQUEST = "CREATE_CUSTOMER_REQUEST";
export const CREATE_CUSTOMER_SUCCESS = "CREATE_CUSTOMER_SUCCESS";
export const CREATE_CUSTOMER_ERROR = "CREATE_CUSTOMER_ERROR";

export const VIEW_CUSTOMER_REQUEST = "VIEW_CUSTOMER_REQUEST";
export const VIEW_CUSTOMER_SUCCESS = "VIEW_CUSTOMER_SUCCESS";
export const VIEW_CUSTOMER_ERROR = "VIEW_CUSTOMER_ERROR";

export const CUSTOMER_LIST_REQUEST = "CUSTOMER_LIST_REQUEST";
export const CUSTOMER_LIST_SUCCESS = "CUSTOMER_LIST_SUCCESS";
export const CUSTOMER_LIST_ERROR = "CUSTOMER_LIST_ERROR";

export const CUSTOMER_STATUS_REQUEST = "CUSTOMER_STATUS_REQUEST";
export const CUSTOMER_STATUS_SUCCESS = "CUSTOMER_STATUS_SUCCESS";
export const CUSTOMER_STATUS_ERROR = "CUSTOMER_STATUS_ERROR";

export const CUSTOMER_DELETE_REQUEST = "CUSTOMER_DELETE_REQUEST";
export const CUSTOMER_DELETE_SUCCESS = "CUSTOMER_DELETE_SUCCESS";
export const CUSTOMER_DELETE_ERROR = "CUSTOMER_DELETE_ERROR";