export const CREATE_DSR_REQUEST = "CREATE_DSR_REQUEST";
export const CREATE_DSR_SUCCESS = "CREATE_DSR_SUCCESS";
export const CREATE_DSR_ERROR = "CREATE_DSR_ERROR";

export const GET_DSR_REQUEST = "GET_DSR_REQUEST";
export const GET_DSR_SUCCESS = "GET_DSR_SUCCESS";
export const GET_DSR_ERROR = "GET_DSR_ERROR";

export const DSR_DETAIL_REQUEST = "DSR_DETAIL_REQUEST";
export const DSR_DETAIL_SUCCESS = "DSR_DETAIL_SUCCESS";
export const DSR_DETAIL_ERROR = "DSR_DETAIL_ERROR";

export const ADD_PASSENGER_REQUEST = "ADD_PASSENGER_REQUEST";
export const ADD_PASSENGER_SUCCESS = "ADD_PASSENGER_SUCCESS";
export const ADD_PASSENGER_ERROR = "ADD_PASSENGER_ERROR";

export const PASSENGER_DELETE_REQUEST = "PASSENGER_DELETE_REQUEST";
export const PASSENGER_DELETE_SUCCESS = "PASSENGER_DELETE_SUCCESS";
export const PASSENGER_DELETE_ERROR = "PASSENGER_DELETE_ERROR";