export const CREATE_DSR_REQUEST = "CREATE_DSR_REQUEST";
export const CREATE_DSR_SUCCESS = "CREATE_DSR_SUCCESS";
export const CREATE_DSR_ERROR = "CREATE_DSR_ERROR";

export const GET_DSR_REQUEST = "GET_DSR_REQUEST";
export const GET_DSR_SUCCESS = "GET_DSR_SUCCESS";
export const GET_DSR_ERROR = "GET_DSR_ERROR";

