export const EXPENSE_LIST_REQUEST = "EXPENSE_LIST_REQUEST";
export const EXPENSE_LIST_SUCCESS = "EXPENSE_LIST_SUCCESS";
export const EXPENSE_LIST_ERROR = "EXPENSE_LIST_ERROR";

export const EXPENSE_CREATE_REQUEST = "EXPENSE_CREATE_REQUEST";
export const EXPENSE_CREATE_SUCCESS = "EXPENSE_CREATE_SUCCESS";
export const EXPENSE_CREATE_ERROR = "EXPENSE_CREATE_ERROR";

export const EXPENSE_DELETE_REQUEST = "EXPENSE_DELETE_REQUEST";
export const EXPENSE_DELETE_SUCCESS = "EXPENSE_DELETE_SUCCESS";
export const EXPENSE_DELETE_ERROR = "EXPENSE_DELETE_ERROR";

export const EXPENSE_DETAIL_REQUEST = "EXPENSE_DETAIL_REQUEST";
export const EXPENSE_DETAIL_SUCCESS = "EXPENSE_DETAIL_SUCCESS";
export const EXPENSE_DETAIL_ERROR = "EXPENSE_DETAIL_ERROR";