

// Constants for updating FLIGHT
export const FLIGHT_UPDATE_REQUEST = 'FLIGHT_UPDATE_REQUEST';
export const FLIGHT_UPDATE_SUCCESS = 'FLIGHT_UPDATE_SUCCESS';
export const FLIGHT_UPDATE_ERROR = 'FLIGHT_UPDATE_ERROR';


export const FLIGHT_STATUS_REQUEST = "FLIGHT_STATUS_REQUEST";
export const FLIGHT_STATUS_SUCCESS = "FLIGHT_STATUS_SUCCESS";
export const FLIGHT_STATUS_ERROR = "FLIGHT_STATUS_ERROR";

export const FLIGHT_DELETE_REQUEST = "FLIGHT_DELETE_REQUEST";
export const FLIGHT_DELETE_SUCCESS = "FLIGHT_DELETE_SUCCESS";
export const FLIGHT_DELETE_ERROR = "FLIGHT_DELETE_ERROR";

export const CREATE_FLIGHT_REQUEST = "CREATE_FLIGHT_REQUEST";
export const CREATE_FLIGHT_SUCCESS = "CREATE_FLIGHT_SUCCESS";
export const CREATE_FLIGHT_ERROR = "CREATE_FLIGHT_ERROR";


export const GET_FLIGHT_REQUEST = "GET_FLIGHT_REQUEST";
export const GET_FLIGHT_SUCCESS = "GET_FLIGHT_SUCCESS";
export const GET_FLIGHT_ERROR = "GET_FLIGHT_ERROR";

export const FLIGHT_DETAIL_REQUEST = "FLIGHT_DETAIL_REQUEST";
export const FLIGHT_DETAIL_SUCCESS = "FLIGHT_DETAIL_SUCCESS";
export const FLIGHT_DETAIL_ERROR = "FLIGHT_DETAIL_ERROR";


