export const CREATE_GRN_REQUEST = "CREATE_GRN_REQUEST";
export const CREATE_GRN_SUCCESS = "CREATE_GRN_SUCCESS";
export const CREATE_GRN_ERROR = "CREATE_GRN_ERROR";

export const GET_GRN_REQUEST = "GET_GRN_REQUEST";
export const GET_GRN_SUCCESS = "GET_GRN_SUCCESS";
export const GET_GRN_ERROR = "GET_GRN_ERROR";

export const GRN_DETAILS_REQUEST = " GRN_DETAILS_REQUEST";
export const GRN_DETAIL_SUCCESS = "GRN_DETAIL_SUCCESS";
export const GRN_DETAILS_ERROR = " GRN_DETAILS_ERROR";

export const GET_GRN_RECEIPT_LIST__REQUEST = "GET_GRN_RECEIPT_LIST__REQUEST";
export const GET_GRN_RECEIPT_LIST__SUCCESS = "GET_GRN_RECEIPT_LIST__SUCCESS";
export const GET_GRN_RECEIPT_LIST__ERROR = "GET_GRN_RECEIPT_LIST__ERROR";

export const GET_GRN_RECEIPT_DETAIL__REQUEST = "GET_GRN_RECEIPT_DETAIL__REQUEST";
export const GET_GRN_RECEIPT_DETAIL__SUCCESS = "GET_GRN_RECEIPT_DETAIL__SUCCESS";
export const GET_GRN_RECEIPT_DETAIL__ERROR = "GET_GRN_RECEIPT_DETAIL__ERROR";

export const GRN_STATUS_REQUEST = "GRN_STATUS_REQUEST";
export const GRN_STATUS_SUCCESS = "GRN_STATUS_SUCCESS";
export const GRN_STATUS_ERROR = "GRN_STATUS_ERROR";

export const GRN_DELETE_REQUEST = "GRN_DELETE_REQUEST";
export const GRN_DELETE_SUCCESS = "GRN_DELETE_SUCCESS";
export const GRN_DELETE_ERROR = "GRN_DELETE_ERROR";

export const MOVE_ITEM_LIST__REQUEST = "MOVE_ITEM_LIST__REQUEST";
export const MOVE_ITEM_LIST__SUCCESS = "MOVE_ITEM_LIST__SUCCESS";
export const MOVE_ITEM_LIST__ERROR = "MOVE_ITEM_LIST__ERROR";

