export const CREATE_HELP_REQUEST = "CREATE_HELP_REQUEST";
export const CREATE_HELP_SUCCESS = "CREATE_HELP_SUCCESS";
export const CREATE_HELP_ERROR = "CREATE_HELP_ERROR";

export const GET_HELP_REQUEST = "GET_HELP_REQUEST";
export const GET_HELP_SUCCESS = "GET_HELP_SUCCESS";
export const GET_HELP_ERROR = "GET_HELP_ERROR";


export const CREATE_HELP_STATUS_REQUEST = "CREATE_HELP_STATUS_REQUEST";
export const CREATE_HELP_STATUS_SUCCESS = "CREATE_HELP_STATUS_SUCCESS";
export const CREATE_HELP_STATUS_ERROR = "CREATE_HELP_STATUS_ERROR";
