

// Constants for updating HOTEL
export const HOTEL_UPDATE_REQUEST = 'HOTEL_UPDATE_REQUEST';
export const HOTEL_UPDATE_SUCCESS = 'HOTEL_UPDATE_SUCCESS';
export const HOTEL_UPDATE_ERROR = 'HOTEL_UPDATE_ERROR';


export const HOTEL_STATUS_REQUEST = "HOTEL_STATUS_REQUEST";
export const HOTEL_STATUS_SUCCESS = "HOTEL_STATUS_SUCCESS";
export const HOTEL_STATUS_ERROR = "HOTEL_STATUS_ERROR";

export const HOTEL_DELETE_REQUEST = "HOTEL_DELETE_REQUEST";
export const HOTEL_DELETE_SUCCESS = "HOTEL_DELETE_SUCCESS";
export const HOTEL_DELETE_ERROR = "HOTEL_DELETE_ERROR";

export const CREATE_HOTEL_REQUEST = "CREATE_HOTEL_REQUEST";
export const CREATE_HOTEL_SUCCESS = "CREATE_HOTEL_SUCCESS";
export const CREATE_HOTEL_ERROR = "CREATE_HOTEL_ERROR";


export const GET_HOTEL_REQUEST = "GET_HOTEL_REQUEST";
export const GET_HOTEL_SUCCESS = "GET_HOTEL_SUCCESS";
export const GET_HOTEL_ERROR = "GET_HOTEL_ERROR";

export const HOTEL_DETAIL_REQUEST = "HOTEL_DETAIL_REQUEST";
export const HOTEL_DETAIL_SUCCESS = "HOTEL_DETAIL_SUCCESS";
export const HOTEL_DETAIL_ERROR = "HOTEL_DETAIL_ERROR";


export const CREATE_HOTEL_ROOM_REQUEST = "CREATE_HOTEL_ROOM_REQUEST";
export const CREATE_HOTEL_ROOM_SUCCESS = "CREATE_HOTEL_ROOM_SUCCESS";
export const CREATE_HOTEL_ROOM_ERROR = "CREATE_HOTEL_ROOM_ERROR";


export const GET_HOTEL_ROOM_REQUEST = "GET_HOTEL_ROOM_REQUEST";
export const GET_HOTEL_ROOM_SUCCESS = "GET_HOTEL_ROOM_SUCCESS";
export const GET_HOTEL_ROOM_ERROR = "GET_HOTEL_ROOM_ERROR";

export const HOTEL_ROOM_DETAIL_REQUEST = "HOTEL_ROOM_DETAIL_REQUEST";
export const HOTEL_ROOM_DETAIL_SUCCESS = "HOTEL_ROOM_DETAIL_SUCCESS";
export const HOTEL_ROOM_DETAIL_ERROR = "HOTEL_ROOM_DETAIL_ERROR";