

// Constants for updating INSURANCE
export const INSURANCE_UPDATE_REQUEST = 'INSURANCE_UPDATE_REQUEST';
export const INSURANCE_UPDATE_SUCCESS = 'INSURANCE_UPDATE_SUCCESS';
export const INSURANCE_UPDATE_ERROR = 'INSURANCE_UPDATE_ERROR';


export const INSURANCE_STATUS_REQUEST = "INSURANCE_STATUS_REQUEST";
export const INSURANCE_STATUS_SUCCESS = "INSURANCE_STATUS_SUCCESS";
export const INSURANCE_STATUS_ERROR = "INSURANCE_STATUS_ERROR";

export const INSURANCE_DELETE_REQUEST = "INSURANCE_DELETE_REQUEST";
export const INSURANCE_DELETE_SUCCESS = "INSURANCE_DELETE_SUCCESS";
export const INSURANCE_DELETE_ERROR = "INSURANCE_DELETE_ERROR";

export const CREATE_INSURANCE_REQUEST = "CREATE_INSURANCE_REQUEST";
export const CREATE_INSURANCE_SUCCESS = "CREATE_INSURANCE_SUCCESS";
export const CREATE_INSURANCE_ERROR = "CREATE_INSURANCE_ERROR";


export const GET_INSURANCE_REQUEST = "GET_INSURANCE_REQUEST";
export const GET_INSURANCE_SUCCESS = "GET_INSURANCE_SUCCESS";
export const GET_INSURANCE_ERROR = "GET_INSURANCE_ERROR";

export const INSURANCE_DETAIL_REQUEST = "INSURANCE_DETAIL_REQUEST";
export const INSURANCE_DETAIL_SUCCESS = "INSURANCE_DETAIL_SUCCESS";
export const INSURANCE_DETAIL_ERROR = "INSURANCE_DETAIL_ERROR";


