export const INVOICE_DETAIL_REQUEST = "INVOICE_DETAIL_REQUEST";
export const INVOICE_DETAIL_SUCCESS = "INVOICE_DETAIL_SUCCESS";
export const INVOICE_DETAIL_ERROR = "INVOICE_DETAIL_ERROR";


export const INVOICE_STATUS_REQUEST = "INVOICE_STATUS_REQUEST";
export const INVOICE_STATUS_SUCCESS = "INVOICE_STATUS_SUCCESS";
export const INVOICE_STATUS_ERROR = "INVOICE_STATUS_ERROR";

export const INVOICE_DELETE_REQUEST = "INVOICE_DELETE_REQUEST";
export const INVOICE_DELETE_SUCCESS = "INVOICE_DELETE_SUCCESS";
export const INVOICE_DELETE_ERROR = "INVOICE_DELETE_ERROR";

export const PENDING_INVOICES_REQUEST = "PENDING_INVOICES_REQUEST";
export const PENDING_INVOICES_SUCCESS = "PENDING_INVOICES_SUCCESS";
export const PENDING_INVOICES_ERROR = "PENDING_INVOICES_ERROR";

export const INVOICE_MAIL_SEND_REQUEST = "INVOICE_MAIL_SEND_REQUEST";
export const INVOICE_MAIL_SEND_SUCCESS = "INVOICE_MAIL_SEND_SUCCESS";
export const INVOICE_MAIL_SEND_ERROR = "INVOICE_MAIL_SEND_ERROR";

export const INVOICE_SEND_REQUEST = "INVOICE_SEND_REQUEST";
export const INVOICE_SEND_SUCCESS = "INVOICE_SEND_SUCCESS";
export const INVOICE_SEND_ERROR = "INVOICE_SEND_ERROR";
