export const ADD_ITMES_REQUEST = "ADD_ITMES_REQUEST";
export const ADD_ITMES_SUCCESS = "ADD_ITMES_SUCCESS";
export const ADD_ITMES_ERROR = "ADD_ITMES_ERROR";

export const STOCK_ITMES_REQUEST = "STOCK_ITMES_REQUEST";
export const STOCK_ITMES_SUCCESS = "STOCK_ITMES_SUCCESS";
export const STOCK_ITMES_ERROR = "STOCK_ITMES_ERROR";

export const ITMES_DETAIL_REQUEST = "ITMES_DETAIL_REQUEST";
export const ITMES_DETAIL_SUCCESS = "ITMES_DETAIL_SUCCESS";
export const ITMES_DETAIL_ERROR = "ITMES_DETAIL_ERROR";

export const ACITVE_INACTIVE_REQUEST = "ACITVE_INACTIVE_REQUEST";
export const ACITVE_INACTIVE_SUCCESS = "ACITVE_INACTIVE_SUCCESS";
export const ACITVE_INACTIVE_FAILURE = "ACITVE_INACTIVE_FAILURE";

export const ITEM_DELETE_REQUEST = "ITEM_DELETE_REQUEST";
export const ITEM_DELETE_SUCCESS = "ITEM_DELETE_SUCCESS";
export const ITEM_DELETE_FAILURE = "ITEM_DELETE_FAILURE";

export const ITEM_IMPORT_REQUEST = "ITEM_IMPORT_REQUEST";
export const ITEM_IMPORT_SUCCESS = "ITEM_IMPORT_SUCCESS";
export const ITEM_IMPORT_FAILURE = "ITEM_IMPORT_FAILURE";

export const ITEM_EXPORT_REQUEST = "ITEM_EXPORT_REQUEST";
export const ITEM_EXPORT_SUCCESS = "ITEM_EXPORT_SUCCESS";
export const ITEM_EXPORT_FAILURE = "ITEM_EXPORT_FAILURE";

export const ITEM_STOCK_REQUEST = "ITEM_STOCK_REQUEST";
export const ITEM_STOCK_SUCCESS = "ITEM_STOCK_SUCCESS";
export const ITEM_STOCK_FAILURE = "ITEM_STOCK_FAILURE";

export const ITEM_ACTIVITY_REQUEST = "ITEM_ACTIVITY_REQUEST";
export const ITEM_ACTIVITY_SUCCESS = "ITEM_ACTIVITY_SUCCESS";
export const ITEM_ACTIVITY_FAILURE = "ITEM_ACTIVITY_FAILURE";