export const FETCH_CAT_LIST_DATA_REQUEST = 'FETCH_CAT_LIST_DATA_REQUEST';
export const FETCH_CAT_LIST_DATA_SUCCESS = 'FETCH_CAT_LIST_DATA_SUCCESS';
export const FETCH_CAT_LIST_DATA_FAILURE = 'FETCH_CAT_LIST_DATA_FAILURE';

export const FETCH_ITEM_LIST_DATA_REQUEST = 'FETCH_ITEM_LIST_DATA_REQUEST';
export const FETCH_ITEM_LIST_DATA_SUCCESS = 'FETCH_ITEM_LIST_DATA_SUCCESS';
export const FETCH_ITEM_LIST_DATA_FAILURE = 'FETCH_ITEM_LIST_DATA_FAILURE';

export const FETCH_ACC_LIST_DATA_REQUEST = 'FETCH_ACC_LIST_DATA_REQUEST';
export const FETCH_ACC_LIST_DATA_SUCCESS = 'FETCH_ACC_LIST_DATA_SUCCESS';
export const FETCH_ACC_LIST_DATA_FAILURE = 'FETCH_ACC_LIST_DATA_FAILURE';

export const FETCH_QUOTE_LIST_DATA_REQUEST = 'FETCH_QUOTE_LIST_DATA_REQUEST';
export const FETCH_QUOTE_LIST_DATA_SUCCESS = 'FETCH_QUOTE_LIST_DATA_SUCCESS';
export const FETCH_QUOTE_LIST_DATA_FAILURE = 'FETCH_QUOTE_LIST_DATA_FAILURE';

export const FETCH_SALE_LIST_DATA_REQUEST = "FETCH_SALE_LIST_DATA_REQUEST";
export const FETCH_SALE_LIST_DATA_SUCCESS = "FETCH_SALE_LIST_DATA_SUCCESS";
export const FETCH_SALE_LIST_DATA_FAILURE = "FETCH_SALE_LIST_DATA_FAILURE";

export const FETCH_INVOICE_LIST_DATA_REQUEST = "FETCH_INVOICE_LIST_DATA_REQUEST";
export const FETCH_INVOICE_LIST_DATA_SUCCESS = "FETCH_INVOICE_LIST_DATA_SUCCESS";
export const FETCH_INVOICE_LIST_DATA_FAILURE = "FETCH_INVOICE_LIST_DATA_FAILURE";

export const FETCH_CREDIT_LIST_DATA_REQUEST = "FETCH_CREDIT_LIST_DATA_REQUEST";
export const FETCH_CREDIT_LIST_DATA_SUCCESS = "FETCH_CREDIT_LIST_DATA_SUCCESS";
export const FETCH_CREDIT_LIST_DATA_FAILURE = "FETCH_CREDIT_LIST_DATA_FAILURE";


export const FETCH_VENDOR_LIST_DATA_REQUEST = "FETCH_VENDOR_LIST_DATA_REQUEST";
export const FETCH_VENDOR_LIST_DATA_SUCCESS = "FETCH_VENDOR_LIST_DATA_SUCCESS";
export const FETCH_VENDOR_LIST_DATA_FAILURE = "FETCH_VENDOR_LIST_DATA_FAILURE";


export const CUSTOM_FIELD_REQUEST = "CUSTOM_FIELD_REQUEST";
export const CUSTOM_FIELD_SUCCESS = "CUSTOM_FIELD_SUCCESS";
export const CUSTOM_FIELD_FAILURE = "CUSTOM_FIELD_FAILURE";

export const PURCHSE_LIST_REQUEST = "PURCHSE_LIST_REQUEST";
export const PURCHSE_LIST_SUCCESS = "PURCHSE_LIST_SUCCESS";
export const PURCHSE_LIST_FAILURE = "PURCHSE_LIST_FAILURE";

export const FETCH_JOURNAL_LIST_DATA_REQUEST = "FETCH_JOURNAL_LIST_DATA_REQUEST";
export const FETCH_JOURNAL_LIST_DATA_SUCCESS = "FETCH_JOURNAL_LIST_DATA_SUCCESS";
export const FETCH_JOURNAL_LIST_DATA_FAILURE = "FETCH_JOURNAL_LIST_DATA_FAILURE";

export const FETCH_PAYMENT_REC_LIST_DATA_REQUEST = "FETCH_PAYMENT_REC_LIST_DATA_REQUEST";
export const FETCH_PAYMENT_REC_LIST_DATA_SUCCESS = "FETCH_PAYMENT_REC_LIST_DATA_SUCCESS";
export const FETCH_PAYMENT_REC_LIST_DATA_FAILURE = "FETCH_PAYMENT_REC_LIST_DATA_FAILURE";



export const FETCH_DEBIT_LIST_DATA_REQUEST = "FETCH_DEBIT_LIST_DATA_REQUEST";
export const FETCH_DEBIT_LIST_DATA_SUCCESS = "FETCH_DEBIT_LIST_DATA_SUCCESS";
export const FETCH_DEBIT_LIST_DATA_ERROR = "FETCH_DEBIT_LIST_DATA_ERROR";