export const CURRENCY_RATE_REQUEST = "CURRENCY_RATE_REQUEST";
export const CURRENCY_RATE_SUCCESS = "CURRENCY_RATE_SUCCESS";
export const CURRENCY_RATE_ERROR = "CURRENCY_RATE_ERROR";

export const CURRENCY_RATE_CREATE_REQUEST = "CURRENCY_RATE_CREATE_REQUEST";
export const CURRENCY_RATE_CREATE_SUCCESS = "CURRENCY_RATE_CREATE_SUCCESS";
export const CURRENCY_RATE_CREATE_ERROR = "CURRENCY_RATE_CREATE_ERROR";