export const REQUISITIONS_LIST_REQUEST = "REQUISITIONS_LIST_REQUEST";
export const REQUISITIONS_LIST_SUCCESS = "REQUISITIONS_LIST_SUCCESS";
export const REQUISITIONS_LIST_ERROR = "REQUISITIONS_LIST_ERROR";

export const REQUISITIONS_DETAIL_REQUEST = "REQUISITIONS_DETAIL_REQUEST";
export const REQUISITIONS_DETAIL_SUCCESS = "REQUISITIONS_DETAIL_SUCCESS";
export const REQUISITIONS_DETAIL_ERROR = "REQUISITIONS_DETAIL_ERROR";


export const REQUISITIONS_APPROVAL_LIST_REQUEST = "EQUISITIONS_APPROVAL_LIST_REQUEST";
export const REQUISITIONS_APPROVAL_LIST_SUCCESS = "EQUISITIONS_APPROVAL_LIST_SUCCESS";
export const REQUISITIONS_APPROVAL_LIST_ERROR = "EQUISITIONS_APPROVAL_LIST_ERROR";

export const STOCK_APPROVAL_CREATE_REQUEST = "STOCK_APPROVAL_CREATE_REQUEST";
export const STOCK_APPROVAL_CREATE_SUCCESS = "STOCK_APPROVAL_CREATE_SUCCESS";
export const STOCK_APPROVAL_CREATE_ERROR = "STOCK_APPROVAL_CREATE_ERROR";
