export const CREATE_MASTER_REQUEST = "CREATE_MASTER_REQUEST";
export const CREATE_MASTER_SUCCESS = "CREATE_MASTER_SUCCESS";
export const CREATE_MASTER_ERROR = "CREATE_MASTER_ERROR";

export const GET_MASTER_REQUEST = "GET_MASTER_REQUEST";
export const GET_MASTER_SUCCESS = "GET_MASTER_SUCCESS";
export const GET_MASTER_ERROR = "GET_MASTER_ERROR";


