export const CREATE_MICE_REQUEST = "CREATE_MICE_REQUEST";
export const CREATE_MICE_SUCCESS = "CREATE_MICE_SUCCESS";
export const CREATE_MICE_ERROR = "CREATE_MICE_ERROR";

export const GET_MICE_REQUEST = "GET_MICE_REQUEST";
export const GET_MICE_SUCCESS = "GET_MICE_SUCCESS";
export const GET_MICE_ERROR = "GET_MICE_ERROR";

export const MICE_DETAIL_REQUEST = "MICE_DETAIL_REQUEST";
export const MICE_DETAIL_SUCCESS = "MICE_DETAIL_SUCCESS";
export const MICE_DETAIL_ERROR = "MICE_DETAIL_ERROR";

export const MICE_DELETE_REQUEST = "MICE_DELETE_REQUEST";
export const MICE_DELETE_SUCCESS = "MICE_DELETE_SUCCESS";
export const MICE_DELETE_ERROR = "MICE_DELETE_ERROR";

export const MICE_STATUS_REQUEST = "MICE_STATUS_REQUEST";
export const MICE_STATUS_SUCCESS = "MICE_STATUS_SUCCESS";
export const MICE_STATUS_ERROR = "MICE_STATUS_ERROR";


export const ADD_PASSENGER_REQUEST = "ADD_PASSENGER_REQUEST";
export const ADD_PASSENGER_SUCCESS = "ADD_PASSENGER_SUCCESS";
export const ADD_PASSENGER_ERROR = "ADD_PASSENGER_ERROR";

export const PASSENGER_DELETE_REQUEST = "PASSENGER_DELETE_REQUEST";
export const PASSENGER_DELETE_SUCCESS = "PASSENGER_DELETE_SUCCESS";
export const PASSENGER_DELETE_ERROR = "PASSENGER_DELETE_ERROR";

export const GET_MICE_SUPPLIER_SUMMARY_REQUEST = "GET_MICE_SUPPLIER_SUMMARY_REQUEST";
export const GET_MICE_SUPPLIER_SUMMARY_SUCCESS = "GET_MICE_SUPPLIER_SUMMARY_SUCCESS";
export const GET_MICE_SUPPLIER_SUMMARY_ERROR = "GET_MICE_SUPPLIER_SUMMARY_ERROR";

export const CLEAR_MICE_STATE = "CLEAR_MICE_STATE";