export const CREATE_ORGNIZATION_REQUEST = "CREATE_ORGNIZATION_REQUEST";
export const CREATE_ORGNIZATION_SUCCESS = "CREATE_ORGNIZATION_SUCCESS";
export const CREATE_ORGNIZATION_FAILURE = "CREATE_ORGNIZATION_FAILURE";

export const ORGNIZATION_LIST_REQUEST = "ORGNIZATION_LIST_REQUEST";
export const ORGNIZATION_LIST_SUCCESS = "ORGNIZATION_LIST_SUCCESS";
export const ORGNIZATION_LIST_FAILURE = "ORGNIZATION_LIST_FAILURE";