export const CREATE_PASSENGERM_FLIGHT_REQUEST = "CREATE_PASSENGERM_FLIGHT_REQUEST";
export const CREATE_PASSENGERM_FLIGHT_SUCCESS = "CREATE_PASSENGERM_FLIGHT_SUCCESS";
export const CREATE_PASSENGERM_FLIGHT_ERROR = "CREATE_PASSENGERM_FLIGHT_ERROR";

export const PASSENGERM_FLIGHT_DELETE_REQUEST = "PASSENGERM_FLIGHT_DELETE_REQUEST";
export const PASSENGERM_FLIGHT_DELETE_SUCCESS = "PASSENGERM_FLIGHT_DELETE_SUCCESS";
export const PASSENGERM_FLIGHT_DELETE_ERROR = "PASSENGERM_FLIGHT_DELETE_ERROR";