export const CREATE_PASSENGERM_HOTEL_REQUEST = "CREATE_PASSENGERM_HOTEL_REQUEST";
export const CREATE_PASSENGERM_HOTEL_SUCCESS = "CREATE_PASSENGERM_HOTEL_SUCCESS";
export const CREATE_PASSENGERM_HOTEL_ERROR = "CREATE_PASSENGERM_HOTEL_ERROR";

export const GET_PASSENGERM_HOTEL_REQUEST = "GET_PASSENGERM_HOTEL_REQUEST";
export const GET_PASSENGERM_HOTEL_SUCCESS = "GET_PASSENGERM_HOTEL_SUCCESS";
export const GET_PASSENGERM_HOTEL_ERROR = "GET_PASSENGERM_HOTEL_ERROR";

export const PASSENGERM_HOTEL_DETAIL_REQUEST = "PASSENGERM_HOTEL_DETAIL_REQUEST";
export const PASSENGERM_HOTEL_DETAIL_SUCCESS = "PASSENGERM_HOTEL_DETAIL_SUCCESS";
export const PASSENGERM_HOTEL_DETAIL_ERROR = "PASSENGERM_HOTEL_DETAIL_ERROR";

export const PASSENGERM_HOTEL_STATUS_REQUEST = "PASSENGERM_HOTEL_STATUS_REQUEST";
export const PASSENGERM_HOTEL_STATUS_SUCCESS = "PASSENGERM_HOTEL_STATUS_SUCCESS";
export const PASSENGERM_HOTEL_STATUS_ERROR = "PASSENGERM_HOTEL_STATUS_ERROR";

export const PASSENGERM_HOTEL_DELETE_REQUEST = "PASSENGERM_HOTEL_DELETE_REQUEST";
export const PASSENGERM_HOTEL_DELETE_SUCCESS = "PASSENGERM_HOTEL_DELETE_SUCCESS";
export const PASSENGERM_HOTEL_DELETE_ERROR = "PASSENGERM_HOTEL_DELETE_ERROR";
