export const CREATE_PASSENGER_VISA_REQUEST = "CREATE_PASSENGER_VISA_REQUEST";
export const CREATE_PASSENGER_VISA_SUCCESS = "CREATE_PASSENGER_VISA_SUCCESS";
export const CREATE_PASSENGER_VISA_ERROR = "CREATE_PASSENGER_VISA_ERROR";

export const PASSENGER_VISA_DELETE_REQUEST = "PASSENGER_VISA_DELETE_REQUEST";
export const PASSENGER_VISA_DELETE_SUCCESS = "PASSENGER_VISA_DELETE_SUCCESS";
export const PASSENGER_VISA_DELETE_ERROR = "PASSENGER_VISA_DELETE_ERROR";