export const CREATE_PASSENGER_HOTEL_REQUEST = "CREATE_PASSENGER_HOTEL_REQUEST";
export const CREATE_PASSENGER_HOTEL_SUCCESS = "CREATE_PASSENGER_HOTEL_SUCCESS";
export const CREATE_PASSENGER_HOTEL_ERROR = "CREATE_PASSENGER_HOTEL_ERROR";

export const GET_PASSENGER_HOTEL_REQUEST = "GET_PASSENGER_HOTEL_REQUEST";
export const GET_PASSENGER_HOTEL_SUCCESS = "GET_PASSENGER_HOTEL_SUCCESS";
export const GET_PASSENGER_HOTEL_ERROR = "GET_PASSENGER_HOTEL_ERROR";

export const PASSENGER_HOTEL_DETAIL_REQUEST = "PASSENGER_HOTEL_DETAIL_REQUEST";
export const PASSENGER_HOTEL_DETAIL_SUCCESS = "PASSENGER_HOTEL_DETAIL_SUCCESS";
export const PASSENGER_HOTEL_DETAIL_ERROR = "PASSENGER_HOTEL_DETAIL_ERROR";

export const PASSENGER_HOTEL_STATUS_REQUEST = "PASSENGER_HOTEL_STATUS_REQUEST";
export const PASSENGER_HOTEL_STATUS_SUCCESS = "PASSENGER_HOTEL_STATUS_SUCCESS";
export const PASSENGER_HOTEL_STATUS_ERROR = "PASSENGER_HOTEL_STATUS_ERROR";

export const PASSENGER_HOTEL_DELETE_REQUEST = "PASSENGER_HOTEL_DELETE_REQUEST";
export const PASSENGER_HOTEL_DELETE_SUCCESS = "PASSENGER_HOTEL_DELETE_SUCCESS";
export const PASSENGER_HOTEL_DELETE_ERROR = "PASSENGER_HOTEL_DELETE_ERROR";
