export const CREATE_PASSENGERM_ASSISTS_REQUEST = "CREATE_PASSENGERM_ASSISTS_REQUEST";
export const CREATE_PASSENGERM_ASSISTS_SUCCESS = "CREATE_PASSENGERM_ASSISTS_SUCCESS";
export const CREATE_PASSENGERM_ASSISTS_ERROR = "CREATE_PASSENGERM_ASSISTS_ERROR";

export const PASSENGERM_ASSISTS_DELETE_REQUEST = "PASSENGERM_ASSISTS_DELETE_REQUEST";
export const PASSENGERM_ASSISTS_DELETE_SUCCESS = "PASSENGERM_ASSISTS_DELETE_SUCCESS";
export const PASSENGERM_ASSISTS_DELETE_ERROR = "PASSENGERM_ASSISTS_DELETE_ERROR";