export const CREATE_PASSENGER_INSURANCE_REQUEST = "CREATE_PASSENGER_INSURANCE_REQUEST";
export const CREATE_PASSENGER_INSURANCE_SUCCESS = "CREATE_PASSENGER_INSURANCE_SUCCESS";
export const CREATE_PASSENGER_INSURANCE_ERROR = "CREATE_PASSENGER_INSURANCE_ERROR";

export const PASSENGER_INSURANCE_DELETE_REQUEST = "PASSENGER_INSURANCE_DELETE_REQUEST";
export const PASSENGER_INSURANCE_DELETE_SUCCESS = "PASSENGER_INSURANCE_DELETE_SUCCESS";
export const PASSENGER_INSURANCE_DELETE_ERROR = "PASSENGER_INSURANCE_DELETE_ERROR";