export const CREATE_PASSENGERM_INSURANCE_REQUEST = "CREATE_PASSENGERM_INSURANCE_REQUEST";
export const CREATE_PASSENGERM_INSURANCE_SUCCESS = "CREATE_PASSENGERM_INSURANCE_SUCCESS";
export const CREATE_PASSENGERM_INSURANCE_ERROR = "CREATE_PASSENGERM_INSURANCE_ERROR";

export const PASSENGERM_INSURANCE_DELETE_REQUEST = "PASSENGERM_INSURANCE_DELETE_REQUEST";
export const PASSENGERM_INSURANCE_DELETE_SUCCESS = "PASSENGERM_INSURANCE_DELETE_SUCCESS";
export const PASSENGERM_INSURANCE_DELETE_ERROR = "PASSENGERM_INSURANCE_DELETE_ERROR";