export const CREATE_PASSENGER_FLIGHT_REQUEST = "CREATE_PASSENGER_FLIGHT_REQUEST";
export const CREATE_PASSENGER_FLIGHT_SUCCESS = "CREATE_PASSENGER_FLIGHT_SUCCESS";
export const CREATE_PASSENGER_FLIGHT_ERROR = "CREATE_PASSENGER_FLIGHT_ERROR";

export const GET_PASSENGER_FLIGHT_REQUEST = "GET_PASSENGER_FLIGHT_REQUEST";
export const GET_PASSENGER_FLIGHT_SUCCESS = "GET_PASSENGER_FLIGHT_SUCCESS";
export const GET_PASSENGER_FLIGHT_ERROR = "GET_PASSENGER_FLIGHT_ERROR";

export const PASSENGER_FLIGHT_DETAIL_REQUEST = "PASSENGER_FLIGHT_DETAIL_REQUEST";
export const PASSENGER_FLIGHT_DETAIL_SUCCESS = "PASSENGER_FLIGHT_DETAIL_SUCCESS";
export const PASSENGER_FLIGHT_DETAIL_ERROR = "PASSENGER_FLIGHT_DETAIL_ERROR";

export const PASSENGER_FLIGHT_STATUS_REQUEST = "PASSENGER_FLIGHT_STATUS_REQUEST";
export const PASSENGER_FLIGHT_STATUS_SUCCESS = "PASSENGER_FLIGHT_STATUS_SUCCESS";
export const PASSENGER_FLIGHT_STATUS_ERROR = "PASSENGER_FLIGHT_STATUS_ERROR";

export const PASSENGER_FLIGHT_DELETE_REQUEST = "PASSENGER_FLIGHT_DELETE_REQUEST";
export const PASSENGER_FLIGHT_DELETE_SUCCESS = "PASSENGER_FLIGHT_DELETE_SUCCESS";
export const PASSENGER_FLIGHT_DELETE_ERROR = "PASSENGER_FLIGHT_DELETE_ERROR";
