export const CREATE_PASSENGERM_OTHER_REQUEST = "CREATE_PASSENGERM_OTHER_REQUEST";
export const CREATE_PASSENGERM_OTHER_SUCCESS = "CREATE_PASSENGERM_OTHER_SUCCESS";
export const CREATE_PASSENGERM_OTHER_ERROR = "CREATE_PASSENGERM_OTHER_ERROR";

export const PASSENGERM_OTHER_DELETE_REQUEST = "PASSENGERM_OTHER_DELETE_REQUEST";
export const PASSENGERM_OTHER_DELETE_SUCCESS = "PASSENGERM_OTHER_DELETE_SUCCESS";
export const PASSENGERM_OTHER_DELETE_ERROR = "PASSENGERM_OTHER_DELETE_ERROR";