export const CREATE_PASSENGERM_CARHIRE_REQUEST = "CREATE_PASSENGERM_CARHIRE_REQUEST";
export const CREATE_PASSENGERM_CARHIRE_SUCCESS = "CREATE_PASSENGERM_CARHIRE_SUCCESS";
export const CREATE_PASSENGERM_CARHIRE_ERROR = "CREATE_PASSENGERM_CARHIRE_ERROR";

export const PASSENGERM_CARHIRE_DELETE_REQUEST = "PASSENGERM_CARHIRE_DELETE_REQUEST";
export const PASSENGERM_CARHIRE_DELETE_SUCCESS = "PASSENGERM_CARHIRE_DELETE_SUCCESS";
export const PASSENGERM_CARHIRE_DELETE_ERROR = "PASSENGERM_CARHIRE_DELETE_ERROR";