export const CREATE_PASSENGERM_VISA_REQUEST = "CREATE_PASSENGERM_VISA_REQUEST";
export const CREATE_PASSENGERM_VISA_SUCCESS = "CREATE_PASSENGERM_VISA_SUCCESS";
export const CREATE_PASSENGERM_VISA_ERROR = "CREATE_PASSENGERM_VISA_ERROR";

export const PASSENGERM_VISA_DELETE_REQUEST = "PASSENGERM_VISA_DELETE_REQUEST";
export const PASSENGERM_VISA_DELETE_SUCCESS = "PASSENGERM_VISA_DELETE_SUCCESS";
export const PASSENGERM_VISA_DELETE_ERROR = "PASSENGERM_VISA_DELETE_ERROR";