export const CREATE_PASSENGER_OTHERS_REQUEST = "CREATE_PASSENGER_OTHERS_REQUEST";
export const CREATE_PASSENGER_OTHERS_SUCCESS = "CREATE_PASSENGER_OTHERS_SUCCESS";
export const CREATE_PASSENGER_OTHERS_ERROR = "CREATE_PASSENGER_OTHERS_ERROR";

export const PASSENGER_OTHERS_DELETE_REQUEST = "PASSENGER_OTHERS_DELETE_REQUEST";
export const PASSENGER_OTHERS_DELETE_SUCCESS = "PASSENGER_OTHERS_DELETE_SUCCESS";
export const PASSENGER_OTHERS_DELETE_ERROR = "PASSENGER_OTHERS_DELETE_ERROR";