export const CREATE_PASSENGER_CARHIRE_REQUEST = "CREATE_PASSENGER_CARHIRE_REQUEST";
export const CREATE_PASSENGER_CARHIRE_SUCCESS = "CREATE_PASSENGER_CARHIRE_SUCCESS";
export const CREATE_PASSENGER_CARHIRE_ERROR = "CREATE_PASSENGER_CARHIRE_ERROR";

export const PASSENGER_CARHIRE_DELETE_REQUEST = "PASSENGER_CARHIRE_DELETE_REQUEST";
export const PASSENGER_CARHIRE_DELETE_SUCCESS = "PASSENGER_CARHIRE_DELETE_SUCCESS";
export const PASSENGER_CARHIRE_DELETE_ERROR = "PASSENGER_CARHIRE_DELETE_ERROR";