export const CREATE_PASSENGER_ASSISTS_REQUEST = "CREATE_PASSENGER_ASSISTS_REQUEST";
export const CREATE_PASSENGER_ASSISTS_SUCCESS = "CREATE_PASSENGER_ASSISTS_SUCCESS";
export const CREATE_PASSENGER_ASSISTS_ERROR = "CREATE_PASSENGER_ASSISTS_ERROR";

export const PASSENGER_ASSISTS_DELETE_REQUEST = "PASSENGER_ASSISTS_DELETE_REQUEST";
export const PASSENGER_ASSISTS_DELETE_SUCCESS = "PASSENGER_ASSISTS_DELETE_SUCCESS";
export const PASSENGER_ASSISTS_DELETE_ERROR = "PASSENGER_ASSISTS_DELETE_ERROR";