export const PAYMENT_CREATE_REQUEST = "PAYMENT_CREATE_REQUEST";
export const PAYMENT_CREATE_SUCCESS = "PAYMENT_CREATE_SUCCESS";
export const PAYMENT_CREATE_ERROR = "PAYMENT_CREATE_ERROR";

export const PAYMENT_DETAIL_REQUEST = "PAYMENT_DETAIL_REQUEST";
export const PAYMENT_DETAIL_SUCCESS = "PAYMENT_DETAIL_SUCCESS";
export const PAYMENT_DETAIL_ERROR = "PAYMENT_DETAIL_ERROR";

export const PAYMENT_DELETE_REQUEST = "PAYMENT_DELETE_REQUEST";
export const PAYMENT_DELETE_SUCCESS = "PAYMENT_DELETE_SUCCESS";
export const PAYMENT_DELETE_ERROR = "PAYMENT_DELETE_ERROR";

export const PAYMENT_STATUS_REQUEST = "PAYMENT_STATUS_REQUEST";
export const PAYMENT_STATUS_SUCCESS = "PAYMENT_STATUS_SUCCESS";
export const PAYMENT_STATUS_ERROR = "PAYMENT_STATUS_ERROR";

export const FETCH_PAYMENT_REC_LIST_DATA_REQUEST = "FETCH_PAYMENT_REC_LIST_DATA_REQUEST"
export const FETCH_PAYMENT_REC_LIST_DATA_SUCCESS = "FETCH_PAYMENT_REC_LIST_DATA_SUCCESS"
export const FETCH_PAYMENT_REC_LIST_DATA_FAILURE = "FETCH_PAYMENT_REC_LIST_DATA_FAILURE";

export const PAYMENT_REC_SEND_REQUEST = "PAYMENT_REC_REQUEST";
export const PAYMENT_REC_SEND_SUCCESS = "PAYMENT_REC_SUCCESS";
export const PAYMENT_REC_SEND_ERROR = "PAYMENT_REC_ERROR";


