export const PURCHASES_CREATE_REQUEST = "PURCHASES_CREATE_REQUEST";
export const PURCHASES_CREATE_SUCCESS = "PURCHASES_CREATE_SUCCESS";
export const PURCHASES_CREATE_ERROR = "PURCHASES_CREATE_ERROR";

export const PURCHASES_DETAIL_REQUEST = "PURCHASES_DETAIL_REQUEST";
export const PURCHASES_DETAIL_SUCCESS = "PURCHASES_DETAIL_SUCCESS";
export const PURCHASES_DETAIL_ERROR = "PURCHASES_DETAIL_ERROR";

export const PURCHASES_DELETE_REQUEST = "PURCHASES_DELETE_REQUEST";
export const PURCHASES_DELETE_SUCCESS = "PURCHASES_DELETE_SUCCESS";
export const PURCHASES_DELETE_ERROR = "PURCHASES_DELETE_ERROR";

export const PURCHASES_SEND_REQUEST = "PURCHASES_SEND_REQUEST";
export const PURCHASES_SEND_SUCCESS = "PURCHASES_SEND_SUCCESS";
export const PURCHASES_SEND_ERROR = "PURCHASES_SEND_ERROR";

export const PURCHASES_STATUS_REQUEST = "PURCHASES_STATUS_REQUEST";
export const PURCHASES_STATUS_SUCCESS = "PURCHASES_STATUS_SUCCESS";
export const PURCHASES_STATUS_ERROR = "PURCHASES_STATUS_ERROR";

