export const QUOTATION_DETAIL_REQUEST = "QUOTATION_DETAIL_REQUEST";
export const QUOTATION_DETAIL_SUCCESS = "QUOTATION_DETAIL_SUCCESS";
export const QUOTATION_DETAIL_ERROR = "QUOTATION_DETAIL_ERROR";


// Constants for updating quotation
export const QUOTATION_UPDATE_REQUEST = 'QUOTATION_UPDATE_REQUEST';
export const QUOTATION_UPDATE_SUCCESS = 'QUOTATION_UPDATE_SUCCESS';
export const QUOTATION_UPDATE_ERROR = 'QUOTATION_UPDATE_ERROR';


export const QUOTATION_STATUS_REQUEST = "QUOTATION_STATUS_REQUEST";
export const QUOTATION_STATUS_SUCCESS = "QUOTATION_STATUS_SUCCESS";
export const QUOTATION_STATUS_ERROR = "QUOTATION_STATUS_ERROR";

export const QUOTATION_DELETE_REQUEST = "QUOTATION_DELETE_REQUEST";
export const QUOTATION_DELETE_SUCCESS = "QUOTATION_DELETE_SUCCESS";
export const QUOTATION_DELETE_ERROR = "QUOTATION_DELETE_ERROR";

export const QUOTATION_SEND_REQUEST = "QUOTATION_SEND_REQUEST";
export const QUOTATION_SEND_SUCCESS = "QUOTATION_SEND_SUCCESS";
export const QUOTATION_SEND_ERROR = "QUOTATION_SEND_ERROR";

