


export const TOURPACKAGE_STATUS_REQUEST = "TOURPACKAGE_STATUS_REQUEST";
export const TOURPACKAGE_STATUS_SUCCESS = "TOURPACKAGE_STATUS_SUCCESS";
export const TOURPACKAGE_STATUS_ERROR = "TOURPACKAGE_STATUS_ERROR";

export const TOURPACKAGE_DELETE_REQUEST = "TOURPACKAGE_DELETE_REQUEST";
export const TOURPACKAGE_DELETE_SUCCESS = "TOURPACKAGE_DELETE_SUCCESS";
export const TOURPACKAGE_DELETE_ERROR = "TOURPACKAGE_DELETE_ERROR";

export const CREATE_TOURPACKAGE_REQUEST = "CREATE_TOURPACKAGE_REQUEST";
export const CREATE_TOURPACKAGE_SUCCESS = "CREATE_TOURPACKAGE_SUCCESS";
export const CREATE_TOURPACKAGE_ERROR = "CREATE_TOURPACKAGE_ERROR";


export const GET_TOURPACKAGE_REQUEST = "GET_TOURPACKAGE_REQUEST";
export const GET_TOURPACKAGE_SUCCESS = "GET_TOURPACKAGE_SUCCESS";
export const GET_TOURPACKAGE_ERROR = "GET_TOURPACKAGE_ERROR";

export const TOURPACKAGE_DETAIL_REQUEST = "TOURPACKAGE_DETAIL_REQUEST";
export const TOURPACKAGE_DETAIL_SUCCESS = "TOURPACKAGE_DETAIL_SUCCESS";
export const TOURPACKAGE_DETAIL_ERROR = "TOURPACKAGE_DETAIL_ERROR";





export const ITINERARY_STATUS_REQUEST = "ITINERARY_STATUS_REQUEST";
export const ITINERARY_STATUS_SUCCESS = "ITINERARY_STATUS_SUCCESS";
export const ITINERARY_STATUS_ERROR = "ITINERARY_STATUS_ERROR";

export const ITINERARY_DELETE_REQUEST = "ITINERARY_DELETE_REQUEST";
export const ITINERARY_DELETE_SUCCESS = "ITINERARY_DELETE_SUCCESS";
export const ITINERARY_DELETE_ERROR = "ITINERARY_DELETE_ERROR";

export const CREATE_ITINERARY_REQUEST = "CREATE_ITINERARY_REQUEST";
export const CREATE_ITINERARY_SUCCESS = "CREATE_ITINERARY_SUCCESS";
export const CREATE_ITINERARY_ERROR = "CREATE_ITINERARY_ERROR";


export const GET_ITINERARY_REQUEST = "GET_ITINERARY_REQUEST";
export const GET_ITINERARY_SUCCESS = "GET_ITINERARY_SUCCESS";
export const GET_ITINERARY_ERROR = "GET_ITINERARY_ERROR";

export const ITINERARY_DETAIL_REQUEST = "ITINERARY_DETAIL_REQUEST";
export const ITINERARY_DETAIL_SUCCESS = "ITINERARY_DETAIL_SUCCESS";
export const ITINERARY_DETAIL_ERROR = "ITINERARY_DETAIL_ERROR";


