

// Constants for updating TOURPACKAGE
export const TOURPACKAGE_UPDATE_REQUEST = 'TOURPACKAGE_UPDATE_REQUEST';
export const TOURPACKAGE_UPDATE_SUCCESS = 'TOURPACKAGE_UPDATE_SUCCESS';
export const TOURPACKAGE_UPDATE_ERROR = 'TOURPACKAGE_UPDATE_ERROR';


export const TOURPACKAGE_STATUS_REQUEST = "TOURPACKAGE_STATUS_REQUEST";
export const TOURPACKAGE_STATUS_SUCCESS = "TOURPACKAGE_STATUS_SUCCESS";
export const TOURPACKAGE_STATUS_ERROR = "TOURPACKAGE_STATUS_ERROR";

export const TOURPACKAGE_DELETE_REQUEST = "TOURPACKAGE_DELETE_REQUEST";
export const TOURPACKAGE_DELETE_SUCCESS = "TOURPACKAGE_DELETE_SUCCESS";
export const TOURPACKAGE_DELETE_ERROR = "TOURPACKAGE_DELETE_ERROR";

export const CREATE_TOURPACKAGE_REQUEST = "CREATE_TOURPACKAGE_REQUEST";
export const CREATE_TOURPACKAGE_SUCCESS = "CREATE_TOURPACKAGE_SUCCESS";
export const CREATE_TOURPACKAGE_ERROR = "CREATE_TOURPACKAGE_ERROR";


export const GET_TOURPACKAGE_REQUEST = "GET_TOURPACKAGE_REQUEST";
export const GET_TOURPACKAGE_SUCCESS = "GET_TOURPACKAGE_SUCCESS";
export const GET_TOURPACKAGE_ERROR = "GET_TOURPACKAGE_ERROR";

export const TOURPACKAGE_DETAIL_REQUEST = "TOURPACKAGE_DETAIL_REQUEST";
export const TOURPACKAGE_DETAIL_SUCCESS = "TOURPACKAGE_DETAIL_SUCCESS";
export const TOURPACKAGE_DETAIL_ERROR = "TOURPACKAGE_DETAIL_ERROR";


