export const CREATE_USER_MASTER_REQUEST = "CREATE_USER_MASTER_REQUEST";
export const CREATE_USER_MASTER_SUCCESS = "CREATE_USER_MASTER_SUCCESS";
export const CREATE_USER_MASTER_ERROR = "CREATE_USER_MASTER_ERROR";

export const GET_USER_MASTER_REQUEST = "GET_USER_MASTER_REQUEST";
export const GET_USER_MASTER_SUCCESS = "GET_USER_MASTER_SUCCESS";
export const GET_USER_MASTER_ERROR = "GET_USER_MASTER_ERROR";

export const DELETE_USER_MASTER_REQUEST = "DELETE_USER_MASTER_REQUEST";
export const DELETE_USER_MASTER_SUCCESS = "DELETE_USER_MASTER_SUCCESS";
export const DELETE_USER_MASTER_ERROR = "DELETE_USER_MASTER_ERROR";


