

// Constants for updating VISA
export const VISA_UPDATE_REQUEST = 'VISA_UPDATE_REQUEST';
export const VISA_UPDATE_SUCCESS = 'VISA_UPDATE_SUCCESS';
export const VISA_UPDATE_ERROR = 'VISA_UPDATE_ERROR';


export const VISA_STATUS_REQUEST = "VISA_STATUS_REQUEST";
export const VISA_STATUS_SUCCESS = "VISA_STATUS_SUCCESS";
export const VISA_STATUS_ERROR = "VISA_STATUS_ERROR";

export const VISA_DELETE_REQUEST = "VISA_DELETE_REQUEST";
export const VISA_DELETE_SUCCESS = "VISA_DELETE_SUCCESS";
export const VISA_DELETE_ERROR = "VISA_DELETE_ERROR";

export const CREATE_VISA_REQUEST = "CREATE_VISA_REQUEST";
export const CREATE_VISA_SUCCESS = "CREATE_VISA_SUCCESS";
export const CREATE_VISA_ERROR = "CREATE_VISA_ERROR";


export const GET_VISA_REQUEST = "GET_VISA_REQUEST";
export const GET_VISA_SUCCESS = "GET_VISA_SUCCESS";
export const GET_VISA_ERROR = "GET_VISA_ERROR";

export const VISA_DETAIL_REQUEST = "VISA_DETAIL_REQUEST";
export const VISA_DETAIL_SUCCESS = "VISA_DETAIL_SUCCESS";
export const VISA_DETAIL_ERROR = "VISA_DETAIL_ERROR";


