export const WAREHOUSE_VIEW_REQUEST = "WAREHOUSE_VIEW_REQUEST";
export const WAREHOUSE_VIEW_SUCCESS = "WAREHOUSE_VIEW_SUCCESS";
export const WAREHOUSE_VIEW_ERROR = "WAREHOUSE_VIEW_ERROR";

export const WAREHOUSE_CREATE_REQUEST = "WAREHOUSE_CREATE_REQUEST";
export const WAREHOUSE_CREATE_SUCCESS = "WAREHOUSE_CREATE_SUCCESS";
export const WAREHOUSE_CREATE_ERROR = "WAREHOUSE_CREATE_ERROR";

export const WAREHOUSE_DETAIL_REQUEST = "WAREHOUSE_DETAIL_REQUEST";
export const WAREHOUSE_DETAIL_SUCCESS = "WAREHOUSE_DETAIL_SUCCESS";
export const WAREHOUSE_DETAIL_ERROR = "WAREHOUSE_DETAIL_ERROR";

export const WAREHOUSE_STATUS_REQUEST = "WAREHOUSE_STATUS_REQUES";
export const WAREHOUSE_STATUS_SUCCESS = "WAREHOUSE_STATUS_SUCCES";
export const WAREHOUSE_STATUS_ERROR = "WAREHOUSE_STATUS_ERROR";


export const ZONE_STATUS_REQUEST = "ZONE_STATUS_REQUES";
export const ZONE_STATUS_SUCCESS = "ZONE_STATUS_SUCCES";
export const ZONE_STATUS_ERROR = "ZONE_STATUS_ERROR";

export const ZONE_VIEW_REQUEST = "ZONE_VIEW_REQUEST";
export const ZONE_VIEW_SUCCESS = "ZONE_VIEW_SUCCESS";
export const ZONE_VIEW_ERROR = "ZONE_VIEW_ERROR";

export const ZONE_CREATE_REQUEST = "ZONE_CREATE_REQUEST";
export const ZONE_CREATE_SUCCESS = "ZONE_CREATE_SUCCESS";
export const ZONE_CREATE_ERROR = "ZONE_CREATE_ERROR";


export const ZONE_DETAIL_REQUEST = "ZONE_DETAIL_REQUEST";
export const ZONE_DETAIL_SUCCESS = "ZONE_DETAIL_SUCCESS";
export const ZONE_DETAIL_ERROR = "ZONE_DETAIL_ERROR";


// RACK

export const RACK_VIEW_REQUEST = "RACK_VIEW_REQUEST";
export const RACK_VIEW_SUCCESS = "RACK_VIEW_SUCCESS";
export const RACK_VIEW_ERROR = "RACK_VIEW_ERROR";

export const RACK_CREATE_REQUEST = "RACK_CREATE_REQUEST";
export const RACK_CREATE_SUCCESS = "RACK_CREATE_SUCCESS";
export const RACK_CREATE_ERROR = "RACK_CREATE_ERROR";

export const RACK_DETAIL_REQUEST = "RACK_DETAIL_REQUEST";
export const RACK_DETAIL_SUCCESS = "RACK_DETAIL_SUCCESS";
export const RACK_DETAIL_ERROR = "RACK_DETAIL_ERROR";

export const RACK_STATUS_REQUEST = "RACK_STATUS_REQUEST";
export const RACK_STATUS_SUCCESS = "RACK_STATUS_SUCCESS";
export const RACK_STATUS_ERROR = "RACK_STATUS_ERROR";

// BIN
export const BIN_VIEW_REQUEST = "BIN_VIEW_REQUEST";
export const BIN_VIEW_SUCCESS = "BIN_VIEW_SUCCESS";
export const BIN_VIEW_ERROR = "BIN_VIEW_ERROR";

export const BIN_CREATE_REQUEST = "BIN_CREATE_REQUEST";
export const BIN_CREATE_SUCCESS = "BIN_CREATE_SUCCESS";
export const BIN_CREATE_ERROR = "BIN_CREATE_ERROR";



export const BIN_DETAIL_REQUEST = "BIN_DETAIL_REQUEST";
export const BIN_DETAIL_SUCCESS = "BIN_DETAIL_SUCCESS";
export const BIN_DETAIL_ERROR = "BIN_DETAIL_ERROR";

export const BIN_STATUS_REQUEST = "BIN_STATUS_REQUEST";
export const BIN_STATUS_SUCCESS = "BIN_STATUS_SUCCESS";
export const BIN_STATUS_ERROR = "BIN_STATUS_ERROR";



